{{ $name := .Values.name }}
{{- $port := .Values.deployment.port | default 80 -}}

kind: Service
apiVersion: v1
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $port }}
      name: app
      targetPort: {{ $port }}
  selector:
    app: {{ $name }}
